/**
 * Upcoming feasts for the homepage.
 *
 * Source of truth is liturgical: each feast is either paschal-relative
 * (a day-offset from Pascha) or fixed in the Julian calendar. We render
 * Gregorian (NS) dates so a parishioner reading the homepage on a
 * secular calendar sees the date they'll see on every wall calendar
 * around them — never the Julian Old-Style number.
 *
 * Mirrors the convention in liturgical.ts: fixed feasts are stored as
 * their NS month+day directly, since the +13 day offset is constant
 * across the 1900–2099 Pascha table window and storing NS sidesteps
 * leap-year edge cases on the Julian side.
 */

import { ORTHODOX_PASCHA } from "./pascha-dates.ts";

// ============================================================================
// Types
// ============================================================================

interface FeastBase {
  /** Display name. */
  name: string;
  /** One-line note shown beneath the date. */
  note: string;
  /**
   * If set, the feast spans this many days starting at its anchor date.
   * Used for ranges like Bright Week (`durationDays: 6`). Defaults to 1
   * (single-day display).
   */
  durationDays?: number;
}

interface PaschalFeast extends FeastBase {
  type: "paschal";
  /**
   * Days from Pascha (Pascha = 0). Negative = before, positive = after.
   * Mirrors the addDays() math in liturgical.ts.
   */
  offset: number;
}

interface FixedFeast extends FeastBase {
  type: "fixed";
  /** Gregorian (New Style) month, 1-12. */
  month: number;
  /** Gregorian (New Style) day, 1-31. */
  day: number;
}

export type Feast = PaschalFeast | FixedFeast;

export interface UpcomingFeast {
  name: string;
  note: string;
  /** Gregorian start date for this occurrence. */
  date: Date;
  /** Gregorian end date if a multi-day range; otherwise equal to `date`. */
  endDate: Date;
  /** Pre-formatted display string, e.g. "May 6" or "April 13 – 18". */
  formatted: string;
}

// ============================================================================
// Catalog of feasts the homepage cares about
// ============================================================================

/**
 * The Twelve Great Feasts (movable + fixed) plus Pascha and a couple of
 * other commemorations the parish observes prominently. Add or remove
 * here — the homepage list is generated by upcoming-window over this
 * catalog.
 */
const FEASTS: Feast[] = [
  // --- Paschal cycle (offsets in days from Pascha) ---
  { type: "paschal", offset: -7,  name: "Palm Sunday",                  note: "The Lord's entry into Jerusalem" },
  { type: "paschal", offset: 0,   name: "Great and Holy Pascha",        note: "The Resurrection of Our Lord" },
  { type: "paschal", offset: 1,   name: "Bright Week",                  note: "Daily Paschal services",        durationDays: 6 },
  { type: "paschal", offset: 24,  name: "Mid-Pentecost",                note: "The middle of the Paschal season" },
  { type: "paschal", offset: 39,  name: "Ascension of Our Lord",        note: "Forty days after Pascha" },
  { type: "paschal", offset: 49,  name: "Holy Pentecost",               note: "The descent of the Holy Spirit" },
  { type: "paschal", offset: 50,  name: "Day of the Holy Trinity",      note: "The Monday after Pentecost" },

  // --- Fixed feasts (NS dates, Twelve Great Feasts and Apostles' Fast end) ---
  { type: "fixed",   month: 7,  day: 12, name: "Holy Apostles Peter & Paul", note: "End of the Apostles' Fast" },
  { type: "fixed",   month: 8,  day: 14, name: "Dormition Fast Begins",       note: "Two-week fast preparing for the Dormition" },
  { type: "fixed",   month: 8,  day: 19, name: "Transfiguration of the Lord", note: "Christ on Mount Tabor" },
  { type: "fixed",   month: 8,  day: 28, name: "Dormition of the Theotokos",  note: "The falling-asleep of the Most Holy Theotokos" },
  { type: "fixed",   month: 9,  day: 21, name: "Nativity of the Theotokos",   note: "The birth of the Most Holy Theotokos" },
  { type: "fixed",   month: 9,  day: 27, name: "Elevation of the Cross",      note: "The Universal Exaltation of the Precious Cross" },
  { type: "fixed",   month: 11, day: 28, name: "Nativity Fast Begins",        note: "Forty-day fast preparing for the Nativity" },
  { type: "fixed",   month: 12, day: 4,  name: "Entry of the Theotokos",      note: "Entry into the Temple" },
  { type: "fixed",   month: 1,  day: 7,  name: "Nativity of Christ",          note: "The Lord's Nativity in the flesh" },
  { type: "fixed",   month: 1,  day: 19, name: "Theophany of the Lord",       note: "The Baptism of Christ in the Jordan" },
  { type: "fixed",   month: 2,  day: 15, name: "Meeting of the Lord",         note: "Presentation in the Temple" },
  { type: "fixed",   month: 4,  day: 7,  name: "Annunciation of the Theotokos", note: "Today is the beginning of our salvation" },
];

// ============================================================================
// Date helpers (kept private — mirror the helpers in liturgical.ts)
// ============================================================================

const MONTH_NAMES = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

function toLocalDateOnly(d: Date): Date {
  return new Date(d.getFullYear(), d.getMonth(), d.getDate());
}

function addDays(d: Date, days: number): Date {
  const out = new Date(d);
  out.setDate(out.getDate() + days);
  return out;
}

function parsePaschaIso(iso: string): Date {
  const [y, m, d] = iso.split("-").map(Number);
  return new Date(y, m - 1, d);
}

/**
 * Compute a feast's Gregorian start date for a given calendar year.
 * Returns null if the year is outside the Pascha table for paschal feasts.
 */
function feastDateForYear(feast: Feast, year: number): Date | null {
  if (feast.type === "paschal") {
    const iso = ORTHODOX_PASCHA[year];
    if (!iso) return null;
    return addDays(parsePaschaIso(iso), feast.offset);
  }
  return new Date(year, feast.month - 1, feast.day);
}

/**
 * Format a feast for display. Single-day feasts → "Month Day". Multi-day
 * spans → "Month Day – Day" (same month) or "Month Day – Month Day"
 * (cross-month).
 */
function formatRange(start: Date, end: Date): string {
  const sm = MONTH_NAMES[start.getMonth()];
  const sd = start.getDate();
  if (start.getTime() === end.getTime()) return `${sm} ${sd}`;
  const em = MONTH_NAMES[end.getMonth()];
  const ed = end.getDate();
  if (start.getMonth() === end.getMonth()) return `${sm} ${sd} – ${ed}`;
  return `${sm} ${sd} – ${em} ${ed}`;
}

// ============================================================================
// Public API
// ============================================================================

/**
 * Return the next `count` upcoming feasts, rendered with Gregorian dates,
 * starting from `today`. Looks at this year and next year so a December
 * "today" can still surface January feasts ahead.
 *
 * On a date today exactly equal to a feast, that feast is included
 * (today counts as upcoming).
 */
export function getUpcomingFeasts(today: Date, count: number = 4): UpcomingFeast[] {
  const start = toLocalDateOnly(today);
  const occurrences: UpcomingFeast[] = [];

  for (const feast of FEASTS) {
    for (const yearOffset of [0, 1]) {
      const year = start.getFullYear() + yearOffset;
      const date = feastDateForYear(feast, year);
      if (!date) continue;
      const duration = feast.durationDays ?? 1;
      const endDate = duration > 1 ? addDays(date, duration - 1) : date;
      // Include feasts whose end date is today or later, so an in-progress
      // multi-day feast (Bright Week mid-week, say) still surfaces.
      if (endDate.getTime() < start.getTime()) continue;
      occurrences.push({
        name: feast.name,
        note: feast.note,
        date,
        endDate,
        formatted: formatRange(date, endDate),
      });
    }
  }

  occurrences.sort((a, b) => a.date.getTime() - b.date.getTime());
  return occurrences.slice(0, count);
}
